export const getAppLinks = () => {
  const common = {
    home: () => "/",
    game: () => "/game",
    animationCount: () => "/animation-count",
    animationNv: () => "/animation-navigation",
    autoEffectText: () => "/text-effect",
    blurryLoading: () => "/blurry-loading",
    cart: () => "/cart",
    rippleButton: () => "/ripple-button",
    chat: () => "/chat",
    choicePicker: () => "/choice-picker",
    contentPlacerholder: () => "/placerholder-content",
    dadJoke: () => "/dad-joke",
    boubleVerticleSlide: () => "/double-vertical-slide",
    doubleClickHeart: () => "/double-click-heart",
    drag: () => "/drag",
    drawBox: () => "/draw-box",
    drinkWater: () => "/drink-water",
    imageEffectWithLength: () => "/image-effect-with-length",
    faqCollapse: () => "/faq-collapse",
    expend: () => "/expend",
    feedBack: () => "/feedBack",
    formWave: () => "/form-wave",
    gitProfile: () => "/gitthub-profile",
    goodCheatFast: () => "/good-cheat-fast",
    searchWiget: () => "/search-wiget",
    hoverBoard: () => "/hover-board",
    imageFeed: () => "/image-feed",
    imageSlider: () => "/imageSlider",
    incrementCounter: () => "/increment-counter",
    keneticLoading: () => "/kenetic-loading",
    keyDown: () => "/key-down",
    mobileNav: () => "/mobile-navigation",
    netflixNav: () => "/netflix-navigation",
    note: () => "/note",
    onlineFilter: () => "/online-filter",
    passwordGenerate: () => "/generate-password",
    pokeDex: () => "/pokemon-dex",
    progressStep: () => "/progress-step",
    quizApp: () => "/quiz-app",
    rangeSlider: () => "/range-slider",
    rotatingNav: () => "/rotate-navigation",
    scrollAnimation: () => "/scroll-animation",
    slideBackground: () => "/slide-background",
    soundBoard: () => "/sound-board",
    splitLanding: () => "/split-landing-page",
    stickyNav: () => "/srticky-navigation",
    Testimonial: () => "/quoute",
    themeClock: () => "/theme-clock",
    toast: () => "/toast",
    todoList: () => "/todo-list",
    translate: () => "/translate",
    verify: () => "/verify",
    movieAPp: () => "/movie-app",
  }

  return {
    common,
  }
}
